<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Sourabh" failures="1" tests="2" name="com.speckyfox.mobiletest.DemoTestMobile" time="153.560" errors="0" timestamp="2024-03-05T15:51:12 IST" skipped="0">
  <testcase classname="com.speckyfox.mobiletest.DemoTestMobile" name="OpenMobileInstance_MOBILE2" time="37.834">
    <failure message="Issue in Mobile 2" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Issue in Mobile 2
at org.junit.Assert.fail(Assert.java:91)
at org.junit.Assert.assertTrue(Assert.java:43)
at com.speckyfox.mobiletest.DemoTestMobile.OpenMobileInstance_MOBILE2(DemoTestMobile.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.speckyfox.framework.DataDrivenIFramework.runner(DataDrivenIFramework.java:117)
at com.speckyfox.testrunner.TestRunner.main(TestRunner.java:10)
]]>
    </failure>
  </testcase> <!-- OpenMobileInstance_MOBILE2 -->
  <system-out/>
  <testcase classname="com.speckyfox.mobiletest.DemoTestMobile" name="OpenMobileInstance_MOBILE" time="115.726"/>
  <system-out/>
</testsuite> <!-- com.speckyfox.mobiletest.DemoTestMobile -->
