<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Sourabh" failures="1" tests="3" name="com.speckyfox.apitest.HicareAPITesting" time="3.382" errors="0" timestamp="2024-03-05T15:51:12 IST" skipped="0">
  <testcase classname="com.speckyfox.apitest.HicareAPITesting" name="TC001_HicareLogin_API" time="1.351"/>
  <system-out/>
  <testcase classname="com.speckyfox.apitest.HicareAPITesting" name="TC002_createAudit" time="0.657">
    <failure message="Audit is not created expected [Audit successfully created] but found [Audit already created for input Audit date &amp; time]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Audit is not created expected [Audit successfully created] but found [Audit already created for input Audit date & time]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.speckyfox.apitest.HicareAPITesting.TC002_createAudit(HicareAPITesting.java:69)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.speckyfox.framework.DataDrivenIFramework.runner(DataDrivenIFramework.java:117)
at com.speckyfox.testrunner.TestRunner.main(TestRunner.java:10)
]]>
    </failure>
  </testcase> <!-- TC002_createAudit -->
  <system-out/>
  <testcase classname="com.speckyfox.apitest.HicareAPITesting" name="TC003_unconfirmAudit" time="1.374"/>
  <system-out/>
</testsuite> <!-- com.speckyfox.apitest.HicareAPITesting -->
